### PR TITLE
implement apis and models, setup django rest framework

### LINKED ISSUE #255: Creating User Models
### Issue Description

Following User model classes should be created:

### Steps

- [x] Basic User

### Deadline for the Issue

17.10.2023

### LINKED ISSUE #256: Signup Page POST API
### Issue Description

A POST method should be implemented on the backend for handling the incoming sign up requests.

### Steps

_No response_

### Deadline for the Issue

17.10.2023

### LINKED ISSUE #257: Login Page POST API
### Issue Description

A POST method should be implemented on backend to handle incoming login requests.

### Steps

_No response_

### Deadline for the Issue

17.10.2023

### LINKED ISSUE #265: Defining authentication mechanisms
### Issue Description

Defining authentication mechanisms
--

<br class="Apple-interchange-newline">

### Steps

- [ ] ...
- [ ] ...
- [ ] ...

### Deadline for the Issue

_No response_

### LINKED ISSUE #275: Get authenticated user GET API
### Issue Description

This issue is created for implementing a GET API to get the authenticated user by supplying authentication token.

### Steps

- [x] implementation

### Deadline for the Issue

15.10.2023

### PR DESCRIPTION
**Pull request by uyduranomer**
this pull request includes implementation of login, signup page apis and get authenticated user get apis. also, basic user model and their serializers were implemented in this pr. 
the merge of this pull request closes #255 , closes #256 , closes #257 , closes #265 , closes #275

### CODE REVIEW

**Comment by ArslanArdavic** [comment]
Thanks for your effort, great job done!

**Review by hakanaktas0 — COMMENTED** [review]
I reviewed the code and tested the functionality, this PR can be merged after the tests are implemented.

**Review by Bera0422 — APPROVED** [review]
I reviewed the code, it works nicely. This PR can be merged after the tests are also reviewed.

**Review by hakanaktas0 — APPROVED** [review]
Tests run as expected and cover the functionality.

**Comment by uyduranomer** [comment]
This pull request has been tested fully and works as expected. I am mergeing this pull request.

**Pull request merged**
