### PR TITLE
New Features

### PR DESCRIPTION
**Pull request by mehmetSuzer**
1- All overflow errors in graph page and workspace page are fixed.

2- A contributor can send a message while sending collaboration request. Provider will be added later.

3- Entry fields support latex now. Edit and preview modes are added. The provider is not added yet.  You can test the code with the following: 

$$(log_23 - 1) + n \le \sum_{i=1}^{n} \log_2(X(u_i, w_i)) \le (log_23 - 1)\frac{n}{m} + n$$

$$(log_23 - 1) + n \le \sum_{i=1}^{n} \log_2(X(u_i, w_i)) \le (\frac{log_23 - 1}{m} + 1)n$$

$$\frac{log_23 - 1}{n} + 1 \le \frac{1}{n} \sum_{i=1}^{n} \log_2(X(u_i, w_i)) \le \frac{log_23 - 1}{m} + 1$$

$$ \lim\limits_{{n \to \infty}} (\frac{log_23 - 1}{n} + 1) \le \lim\limits_{{n \to \infty}} \frac{1}{n} \sum_{i=1}^{n} \log_2(X(u_i, w_i)) \le  \lim\limits_{{n \to \infty}} \frac{log_23 - 1}{m} + 1$$

$$1 \le  \lim\limits_{{n \to \infty}} \frac{1}{n} \sum_{i=1}^{n} \log_2(X(u_i, w_i)) \le \frac{log_23 - 1}{m} + 1$$

You should be able to copy the raw form of this when you click "edit" for this comment.
There is also a function named getMockLatex() which returns the same thing above. You can use it to test it as well.

4- CardContainer's background can be colourable now.

### CODE REVIEW

**Comment by Zulalm** [comment]
Your work looks perfect except a minor bug on the mobile browser. 
image
Some of the lines of the entries is not shown. Could you please check them?

**Comment by mehmetSuzer** [comment]
@Zulalm, The content of an entry is scrollable both horizontally and vertically. So you should be able to see the rest of the lines when you scroll.

**Comment by Zulalm** [comment]
The content is scrollable on the mobile device but not on the mobile browser.

**Review by Zulalm — APPROVED** [review]

**Comment by mehmetSuzer** [comment]
I had difficulty solving conflicts and old frontend branch problem. So, I carried my work to another branch and PR #610 .

**Pull request closed without merging**
