### PR TITLE
Entry Class Implementation

### LINKED ISSUE #401: Entry Class Implementation
### Issue Description

Theorem Class/Model should be implemented according to [the Class Diagram](https://github.com/bounswe/bounswe2023group9/wiki/Class-Diagram).

### Steps

- [X] Implementing the attributes
- [X] Implementing the related functions
- [X] Writing and running unit tests

### Deadline for the Issue
14.11.2023

### PR DESCRIPTION
**Pull request by gebenalimert**
Implemented workspace model, fixes #401. May need enhancements in the future.

### CODE REVIEW

**Comment by ArslanArdavic** [comment]
Looks like some problems have emerged. Let's be sure that all migrations made.

**Comment by gebenalimert** [comment]
Checks have been completed after resolving conflicts.

**Review by ArslanArdavic — APPROVED** [review]
Reviewed your work. Everything all-right.

**Comment by gebenalimert** [comment]
> Entry Index to be specified.
Done.

**Pull request merged**
