### PR TITLE
Implement GET for Node

### PR DESCRIPTION
**Pull request by Bera0422**
Implemented GET method for Nodes, add tests, and a serializer for Node model.

### CODE REVIEW

**Review by hakanaktas0 — APPROVED** [review]
Looks good to merge.

**Review by hakanaktas0 — CHANGES_REQUESTED** [review]
The API call doesn't return the proof ids.

**Comment by uyduranomer** [comment]
This PR includes conflicts with my latest updates on the branch since this PR were opened before that commit. @Bera0422 please let me know when you want to merge this PR and let us resolve conflicts together.

**Comment by Bera0422** [comment]
> The API call doesn't return the proof ids.

Proof Ids are added.

**Review by uyduranomer — APPROVED** [review]
Requested changes were implemented and everything looks nice. When the tests are passed, the pr can be merged.

**Review by hakanaktas0 — APPROVED** [review]
With the addition of proof ids, This PR can be merged.

**Pull request merged**
